### ISSUE TITLE
Please add a shot description and the 'racket' topic

### ISSUE THREAD

**Issue by spdegabrielle** [conniepocky/waffle-racket#1]
Hi, 
I like you waffle! 🥇 

Please add a short description to this repository. Something like 'A waffle'.

It would also be nice if you could add the `racket` topic so others can find it more easily. (click 'manage topics' just under the description on https://github.com/conniepocky/waffle-racket 

Kind regards, 

Stephen

**Comment by conniepocky** [comment]
Hi Stephen :)

I fixed it and added the racket topic :D

**Comment by spdegabrielle** [comment]
Thank you
